version: '3'

services:
  db:
    image: postgres:13-buster
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db-data:
