# Generated by Django 4.2.1 on 2023-05-09 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("doctors", models.ManyToManyField(to="doctors.medicalprofessional")),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_condition",
                    models.CharField(
                        choices=[
                            ("HE", "Healthy"),
                            ("UC", "Unchecked"),
                            ("UH", "Unhealthy"),
                            ("IH", "In Hospital"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "medical_record",
                    models.FileField(
                        blank=True, null=True, upload_to="static/medical_files/"
                    ),
                ),
                (
                    "x_ray",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/x_rays/"
                    ),
                ),
                (
                    "medical_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/medical_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
