# Generated by Django 4.2.1 on 2023-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="doctors",
            field=models.ManyToManyField(
                blank=True, null=True, to="doctors.medicalprofessional"
            ),
        ),
    ]
